# Generated by Django 6.0.2 on 2026-03-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='location',
        ),
        migrations.AddField(
            model_name='pet',
            name='incident_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
