# Generated by Django 6.0.2 on 2026-03-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
